import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import {team} from '@/content/site';
import {Reveal} from '@/components/Reveal';
import YouTube from '@/components/YouTube';
import CTA from '@/components/CTA';
import FounderStory from '@/components/FounderStory';
import ExpertSpotlight from '@/components/ExpertSpotlight';
export const metadata:Metadata={title:'About GVE',description:'Founded by Seattle builder Craig Mauer in 2023. Virtual assistants for business owners, with screening and ongoing GVE support.',alternates:{canonical:'/about/'}};
const history=[{year:'2020',title:'Help for his own business.',body:'Craig hired Alma to support his construction business, Silver Peak Design Build.'},{year:'2021',title:'Kate joins Silver Peak.',body:'Kate joined as a drafter and grew into pre-production management.'},{year:'2023',title:'GVE begins.',body:'Craig started GVE to bring the same kind of support to other business owners.'}];
export default function About(){return <><section className="page-intro"><div className="studio-wrap about-editorial"><div><p className="kicker">About GVE</p><h1>Why we started<br/>Global Virtual<br/>Experts.</h1><p>Craig Mauer hired virtual assistants for his construction business, Silver Peak Design Build. In 2023, he started GVE to help other business owners find support.</p><Link href="/contact-us" className="underlined">Find support for your business</Link></div><figure className="founder-profile"><Image src="/team/craig.jpeg" alt="Craig Mauer" width={678} height={680} priority/><figcaption><strong>Craig Mauer</strong><span>CEO, Global Virtual Experts<br/>Owner, Silver Peak Design Build</span></figcaption></figure></div></section><FounderStory/><section className="chapter"><div className="studio-wrap"><ol className="timeline">{history.map(h=><Reveal as="li" key={h.year}><span className="year">{h.year}</span><h2>{h.title}</h2><p>{h.body}</p></Reveal>)}</ol></div></section><section className="chapter people-chapter"><div className="studio-wrap"><div className="chapter-heading"><div><p className="kicker">Our people</p><h2>The GVE<br/>team.</h2></div><div><p>Our team works in admin, finance, design, sales, and operations.</p><Link href="/stories" className="underlined">Hear their stories</Link></div></div><ul className="team-directory">{team.map((p,i)=><Reveal as="li" key={p.name} delay={(i%4)*.04}><Image src={p.img} alt={p.name} width={300} height={300}/><h3>{p.name}</h3><p>{p.role}</p></Reveal>)}</ul><div className="team-film"><YouTube id="rOlaO2CRFUA" title="Meet the GVE team"/></div><ExpertSpotlight/></div></section><CTA/></>}
