import type {Metadata} from 'next';
import Image from 'next/image';
import Link from 'next/link';
import {team} from '@/content/site';
import {Reveal} from '@/components/Reveal';
import YouTube from '@/components/YouTube';
import CTA from '@/components/CTA';
export const metadata:Metadata={title:'About GVE',description:'Founded by Seattle builder Craig Mauer in 2023. Virtual support built around real business needs.'};
const history=[{year:'2020',title:'Help for his own business.',body:'Craig hired Alma to support his construction business, Silver Peak Design Build.'},{year:'2021',title:'More skills. More support.',body:'Kate joined as a drafter and grew into pre-production management.'},{year:'2023',title:'GVE begins.',body:'Craig started GVE to bring the same kind of support to other business owners.'}];
export default function About(){return <><section className="page-intro"><div className="studio-wrap about-editorial"><div><p className="kicker">About GVE</p><h1>It started with<br/>a builder<br/>needing help.</h1><p>Craig Mauer knew the pressure of running a construction business. Hiring virtual support changed how he worked. That experience became Global Virtual Experts.</p><Link href="/contact" className="underlined">Find support for your business</Link></div><figure className="founder-profile"><Image src="/team/craig.jpeg" alt="Craig Mauer" width={678} height={680} priority/><figcaption><strong>Craig Mauer</strong><span>CEO & Founder</span></figcaption></figure></div></section><section className="chapter"><div className="studio-wrap"><ol className="timeline">{history.map(h=><Reveal as="li" key={h.year}><span className="year">{h.year}</span><h2>{h.title}</h2><p>{h.body}</p></Reveal>)}</ol></div></section><section className="chapter people-chapter"><div className="studio-wrap"><div className="chapter-heading"><div><p className="kicker">The people behind GVE</p><h2>Good work.<br/>Good people.</h2></div><div><p>Our mission is to help businesses thrive and create meaningful opportunities for our Experts.</p><Link href="/stories" className="underlined">Hear their stories</Link></div></div><ul className="team-directory">{team.map((p,i)=><Reveal as="li" key={p.name} delay={(i%4)*.04}><Image src={p.img} alt={p.name} width={300} height={300}/><h3>{p.name}</h3><p>{p.role}</p></Reveal>)}</ul><div className="team-film"><YouTube id="rOlaO2CRFUA" title="Meet the GVE team"/></div></div></section><CTA title="Built around your business."/></>}
