export type WorkDomain='plans'|'projects'|'finance'|'clients'|'marketing'|'digital'|'logistics';
export const domains=[
 {id:'plans' as const,group:'model_plans',label:'CAD & drawings',short:'Plans',slug:'cad-drafting',title:'From ideas to detailed drawings.',body:'Drafting support for plans, models, as-builts, and revisions.',tasks:['2D plans and 3D models','Construction documents','As-built drawings and revisions']},
 {id:'projects' as const,group:'project_schedule',label:'Project coordination',short:'Projects',slug:'project-management',title:'Keep the next job moving.',body:'Schedules, vendor coordination, and project updates.',tasks:['Update project schedules','Coordinate vendors and stakeholders','Track tasks and milestones']},
 {id:'finance' as const,group:'finance_folio',label:'Bookkeeping',short:'Accounts',slug:'bookkeeping',title:'Keep your books in order.',body:'Support for invoices, account reconciliation, and financial reporting.',tasks:['Track bills, receipts, and payments','Reconcile accounts monthly','Prepare financial reports']},
 {id:'clients' as const,group:'client_followups',label:'Client follow-ups',short:'Customers',slug:'executive-assistant',title:'Every conversation followed through.',body:'Help with your inbox, client inquiries, and follow-ups.',tasks:['Answer client emails and inquiries','Send follow-ups on time','Keep your calendar current']}
];
export const allDomains=[...domains,
 {id:'marketing' as const,group:'brand_marketing',label:'Brand & content',short:'Content',slug:'graphic-design',title:'Show up with a clear brand.',body:'Graphics, content, and campaigns for your business.',tasks:['Brand and marketing materials','Social content','Customer communications']},
 {id:'digital' as const,group:'digital_workspace',label:'Website support',short:'Websites',slug:'web-development',title:'Keep your website working.',body:'Website builds, updates, and fixes.',tasks:['Website development','CMS updates','Maintenance and fixes']},
 {id:'logistics' as const,group:'dispatch_routes',label:'Dispatch & logistics',short:'Dispatch',slug:'dispatch-logistics',title:'Keep deliveries coordinated.',body:'Drivers, deliveries, and customer updates.',tasks:['Coordinate drivers','Track shipments','Keep customers informed']}
];
export function domainForService(slug:string):WorkDomain{if(slug==='cad-drafting')return 'plans';if(slug==='project-management')return 'projects';if(slug==='dispatch-logistics')return 'logistics';if(slug==='bookkeeping')return 'finance';if(['graphic-design','marketing','copywriting'].includes(slug))return 'marketing';if(slug==='web-development')return 'digital';return 'clients';}
